### ISSUE TITLE
Wrong "Open in Colab" link in London Air Quality Tutorial 

### ISSUE THREAD

**Issue by laurenharrell** [google/bayesnf#41]
![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg) link in the London Air Quality tutorial notebook, BayesNF_Tutorial_on_London_Air_Quality.ipynb, (as well as .md and .html) routes to the Hungarian Chickenpox tutorial instead of the correct notebook.

**Comment by ColCarroll** [comment]
Thanks @laurenharrell for the report and @fsaad for the fix -- should be better now!
